### ISSUE TITLE
No text and no events from the navigator

### ISSUE THREAD

**Issue by Wertzui123** [many1337/LobbyCoreUI#22]
When I use the navigator, there are only blank buttons, and when I click them, nothing happends!

**Comment by many1337** [comment]
hm

**Comment by many1337** [comment]
Error code?

**Comment by Wertzui123** [comment]
There is no error

**Comment by Wertzui123** [comment]
So for the blank buttons I found the error: I must set the Bedwars for example in "

So like this:


#################################
# Configuration for LobbyCore #
#################################

# use § for text color

# Item names (for the teleport items):

Game-1-Name: "Survival"
Game-2-Name: "Plots"
Game-3-Name: "SkyPvP"
Game-4-Name: "BedWars"
Game-5-Name: "MLG-Rush"

# Transfer (for the teleport / UI form):

ip-port: transferserver entengames.net 19132
ip-port2: transferserver entenames.net 101
ip-port3: transferserver entengames.net 102
ip-port4: transferserver entengames.net 103
ip-port5: transferserver wertzuigames.citybuild.one 25632

# Effects Menu Config

EffectName:
EffectName2:
EffectName3:
EffectName4:

# Effect add later!

# Loading Screen

# Loading Screen types: 
# OVERWORLD "Default Screen"
# NETHER
# THE_END

loadingScreen1: OVERWORLD
loadingScreen2: OVERWORLD
loadingScreen3: OVERWORLD
loadingScreen4: OVERWORLD
loadingScreen5: OVERWORLD



But when I click the buttons, always nothing happends!

**Comment by many1337** [comment]
Now fixed!

**Comment by Wertzui123** [comment]
Ok, thanks!
